import React, { useState } from 'react';
import { Booking } from '../types';
import { Modal } from './ui/Modal';
import { ref, uploadBytes, getDownloadURL } from "firebase/storage";
import { storage, isMockMode } from "../firebase";

interface BookingsViewProps {
  bookings: Booking[];
  onAdd: (booking: Booking) => void;
  onDelete: (id: string) => void;
}

export const BookingsView: React.FC<BookingsViewProps> = ({ bookings, onAdd, onDelete }) => {
  const [filter, setFilter] = useState<'all'|'flight'|'hotel'|'ticket'>('all');
  
  // Modal State
  const [isAddOpen, setIsAddOpen] = useState(false);
  const [newBooking, setNewBooking] = useState<Partial<Booking>>({ type: 'flight', attachments: [] });
  const [uploading, setUploading] = useState(false);

  const filteredBookings = bookings.filter(b => filter === 'all' || b.type === filter);

  // --- Image Upload & Compression Logic ---
  const compressImage = (file: File): Promise<Blob> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = (event) => {
        const img = new Image();
        img.src = event.target?.result as string;
        img.onload = () => {
          const canvas = document.createElement('canvas');
          const MAX_WIDTH = 1024;
          let width = img.width;
          let height = img.height;

          if (width > MAX_WIDTH) {
            height *= MAX_WIDTH / width;
            width = MAX_WIDTH;
          }

          canvas.width = width;
          canvas.height = height;
          const ctx = canvas.getContext('2d');
          ctx?.drawImage(img, 0, 0, width, height);
          
          canvas.toBlob((blob) => {
            if (blob) resolve(blob);
            else reject(new Error('Compression failed'));
          }, 'image/jpeg', 0.7); // 70% quality
        };
      };
      reader.onerror = (error) => reject(error);
    });
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      setUploading(true);
      try {
        const file = e.target.files[0];
        const compressedBlob = await compressImage(file);
        
        // Mock Mode: Bypass Firebase Storage
        if (isMockMode) {
           const reader = new FileReader();
           reader.onload = (e) => {
              const result = e.target?.result as string;
              setNewBooking(prev => ({
                ...prev,
                attachments: [...(prev.attachments || []), result]
              }));
              setUploading(false);
           };
           reader.readAsDataURL(compressedBlob);
           return;
        }

        // Upload to Firebase Storage
        const fileName = `bookings/${Date.now()}_${file.name}`;
        const storageRef = ref(storage, fileName);
        await uploadBytes(storageRef, compressedBlob);
        const downloadUrl = await getDownloadURL(storageRef);

        // Add to newBooking state
        setNewBooking(prev => ({
          ...prev,
          attachments: [...(prev.attachments || []), downloadUrl]
        }));
      } catch (error) {
        console.error("Upload failed", error);
        alert(isMockMode ? "上傳失敗" : "上傳失敗，請檢查網路或 Storage 權限");
      } finally {
        if (!isMockMode) setUploading(false);
      }
    }
  };

  const handleAdd = () => {
    if (!newBooking.title) return;
    const item: Booking = {
      id: '', // Will be generated by App
      type: newBooking.type || 'flight',
      title: newBooking.title,
      referenceNo: newBooking.referenceNo || '',
      date: newBooking.date || new Date().toISOString().split('T')[0],
      details: { ...newBooking.details },
      attachments: newBooking.attachments || [],
      cost: 0,
      currency: 'HKD',
      paidByMemberId: '1'
    };
    onAdd(item);
    setIsAddOpen(false);
    setNewBooking({ type: 'flight', attachments: [] });
  };

  const handleDelete = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    onDelete(id);
  };

  return (
    <div className="px-4 pt-2 pb-20">
      {/* Filters */}
      <div className="flex space-x-2 overflow-x-auto no-scrollbar mb-4 py-1">
        {['all', 'flight', 'hotel', 'ticket'].map(f => (
          <button 
            key={f}
            onClick={() => setFilter(f as any)}
            className={`px-4 py-1.5 rounded-full text-xs font-bold whitespace-nowrap transition-colors ${filter === f ? 'bg-muji-accent text-white' : 'bg-white border border-gray-200 text-gray-500'}`}
          >
            {f === 'all' ? '全部' : f.charAt(0).toUpperCase() + f.slice(1)}
          </button>
        ))}
      </div>

      <div className="space-y-4">
        {filteredBookings.map(item => (
          <div key={item.id} className="relative">
            {/* Boarding Pass Style Card */}
            <div className="bg-white rounded-xl overflow-hidden shadow-soft border border-gray-100">
               {/* Card Top: Header */}
               <div className={`p-4 ${item.type === 'flight' ? 'bg-blue-50' : item.type === 'hotel' ? 'bg-orange-50' : 'bg-gray-50'} border-b border-dashed border-gray-300 relative`}>
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-gray-500">{item.type} TICKET</span>
                    <span className="font-mono text-xs font-bold text-gray-400">{item.date}</span>
                  </div>
                  <h3 className="text-lg font-bold text-muji-text">{item.title}</h3>
                  
                  {/* Decorative Circle Cutouts */}
                  <div className="absolute -bottom-1.5 -left-1.5 w-3 h-3 bg-muji-bg rounded-full"></div>
                  <div className="absolute -bottom-1.5 -right-1.5 w-3 h-3 bg-muji-bg rounded-full"></div>
               </div>

               {/* Card Body */}
               <div className="p-4">
                  <div className="flex justify-between items-end">
                    <div>
                       <p className="text-xs text-gray-400 mb-0.5">Reference No.</p>
                       <p className="font-mono text-base font-bold text-muji-text tracking-wide">{item.referenceNo || 'N/A'}</p>
                    </div>
                    {item.details.location && (
                      <div className="text-right">
                         <p className="text-xs text-gray-400 mb-0.5">Location</p>
                         <p className="font-bold text-sm">{item.details.location}</p>
                      </div>
                    )}
                  </div>

                  {/* Attachments */}
                  {item.attachments && item.attachments.length > 0 && (
                    <div className="mt-4 pt-3 border-t border-gray-100">
                      <p className="text-xs text-gray-400 mb-2">Attachments</p>
                      <div className="flex gap-2 overflow-x-auto">
                        {item.attachments.map((url, idx) => (
                          <a key={idx} href={url} target="_blank" rel="noreferrer" className="block w-12 h-12 flex-shrink-0 bg-gray-100 rounded-lg overflow-hidden border border-gray-200 relative group">
                            <img src={url} alt="attachment" className="w-full h-full object-cover" />
                          </a>
                        ))}
                      </div>
                    </div>
                  )}
                  
                  <div className="mt-4 pt-3 border-t border-gray-100 flex justify-end items-center">
                    <button 
                      onClick={(e) => handleDelete(e, item.id)} 
                      className="text-xs text-red-400 hover:text-red-600 font-bold px-3 py-2 -mr-2"
                    >
                      Delete
                    </button>
                  </div>
               </div>
            </div>
          </div>
        ))}

        {filteredBookings.length === 0 && (
          <div className="text-center py-10 text-gray-400 text-sm">暫無預訂資料</div>
        )}
      </div>

      <div className="fixed bottom-24 right-4 z-30">
        <button onClick={() => setIsAddOpen(true)} className="bg-muji-accent text-white w-12 h-12 rounded-full shadow-lg flex items-center justify-center text-2xl pb-1 active:scale-90 transition-transform">
          +
        </button>
      </div>

      {/* Add Modal */}
      <Modal isOpen={isAddOpen} onClose={() => setIsAddOpen(false)} title="新增預訂">
        <div className="space-y-3">
          <select 
            className="w-full p-3 bg-gray-50 rounded-lg"
            value={newBooking.type}
            onChange={e => setNewBooking({...newBooking, type: e.target.value as any})}
          >
            <option value="flight">機票</option>
            <option value="hotel">住宿</option>
            <option value="ticket">門票</option>
          </select>
          <input 
            placeholder="標題 (例: 首爾機票)" 
            className="w-full p-3 bg-gray-50 rounded-lg"
            value={newBooking.title || ''}
            onChange={e => setNewBooking({...newBooking, title: e.target.value})}
          />
           <input 
            placeholder="訂單編號" 
            className="w-full p-3 bg-gray-50 rounded-lg"
            value={newBooking.referenceNo || ''}
            onChange={e => setNewBooking({...newBooking, referenceNo: e.target.value})}
          />
           <input 
            type="date"
            className="w-full p-3 bg-gray-50 rounded-lg"
            value={newBooking.date || ''}
            onChange={e => setNewBooking({...newBooking, date: e.target.value})}
          />
          
          <div className="border-t border-gray-100 pt-2">
            <label className="block text-xs font-bold text-gray-500 mb-2">附件 (憑證圖片)</label>
            <div className="flex flex-wrap gap-2 mb-2">
              {newBooking.attachments?.map((url, idx) => (
                <div key={idx} className="w-16 h-16 bg-gray-100 rounded relative overflow-hidden border border-gray-200">
                   <img src={url} alt="preview" className="w-full h-full object-cover" />
                </div>
              ))}
              
              <label className="w-16 h-16 bg-gray-50 border border-dashed border-gray-300 rounded flex flex-col items-center justify-center cursor-pointer hover:bg-gray-100">
                {uploading ? (
                  <span className="block w-4 h-4 border-2 border-gray-400 border-t-transparent rounded-full animate-spin"></span>
                ) : (
                  <>
                    <span className="text-xl text-gray-400">+</span>
                    <span className="text-[8px] text-gray-400">上傳</span>
                  </>
                )}
                <input type="file" accept="image/*" onChange={handleFileUpload} className="hidden" disabled={uploading} />
              </label>
            </div>
            <p className="text-[10px] text-gray-400">圖片將自動壓縮並上傳</p>
          </div>

          <button onClick={handleAdd} className="w-full bg-muji-accent text-white py-3 rounded-lg font-bold shadow-soft active:translate-y-1 active:shadow-none transition-all mt-2">
            確認新增
          </button>
        </div>
      </Modal>
    </div>
  );
};